name: HTML/PYTHON application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: docker login
      env:
#        Docker_Hub_Username: xxxxxx
#        Docker_Hub_Password: xxxxxx
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        repository: cj22011992/html-app:latest
        tags: latest, ${{ secrets.run_number }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker image build -t cj22011992/html-app:latest .
        docker push cj22011992/html-app:latest